import type { TSBStore } from "./types";

const CID = {
  rome: "city-rome-0001",
  london: "city-london-0002",
  tokyo: "city-tokyo-0003",
};

export function createSeedStore(): TSBStore {
  const now = new Date();
  const future = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  const past = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000);

  const orgTsb = "org-tsb-platform";
  const orgAurelia = "org-aurelia-hospitality";
  const orgThames = "org-thames-luxury";
  const orgRomaElite = "org-roma-elite";
  const orgImperial = "org-imperial-city";
  const orgHidden = "org-hidden-rome";

  const toRomaElite = "to-roma-elite";
  const toImperial = "to-imperial-city";
  const toHidden = "to-hidden-rome";

  const hotelAurelia = "prop-aurelia-roma";
  const hotelNavona = "prop-palazzo-navona";
  const hotelKensington = "prop-kensington-grand";

  const tourColosseum = "tour-colosseum-private";
  const tourVatican = "tour-vatican-early";
  const tourFood = "tour-food-wine";
  const tourGolf = "tour-golf-cart";
  const tourTivoli = "tour-tivoli";
  const tourUnderground = "tour-underground";

  const catAncient = "cat-ancient-rome";
  const catVatican = "cat-vatican";
  const catFood = "cat-food";
  const catUnique = "cat-unique";
  const catDayTrips = "cat-day-trips";

  const baseOrders = [
    {
      id: "order-success-future",
      correlationId: "corr-001",
      overallStatus: "confirmed" as const,
      holdStatus: "released",
      bookingStatus: "confirmed",
      paymentStatus: "captured",
      transferStatus: "scheduled",
      hotelPropertyId: hotelAurelia,
      tourOperatorId: toRomaElite,
      tourId: tourColosseum,
      grossAmountCents: 14900,
      capturedAt: now.toISOString(),
      transferEligibleAt: new Date(now.getTime() + 48 * 60 * 60 * 1000).toISOString(),
      serviceEndAt: future.toISOString(),
      voucherCode: "TSB-VCH-001",
      touristEmail: "tourist1@demo.com",
    },
    {
      id: "order-active-hold",
      correlationId: "corr-002",
      overallStatus: "awaiting_payment" as const,
      holdStatus: "active",
      bookingStatus: "not_started",
      paymentStatus: "not_started",
      transferStatus: "blocked",
      hotelPropertyId: hotelAurelia,
      tourOperatorId: toRomaElite,
      tourId: tourVatican,
      grossAmountCents: 12500,
      holdId: "HOLD-DEMO-002",
      holdExpiresAt: new Date(now.getTime() + 12 * 60 * 1000).toISOString(),
      serviceEndAt: future.toISOString(),
    },
    {
      id: "order-auth-failed",
      correlationId: "corr-003",
      overallStatus: "cancelled" as const,
      holdStatus: "released",
      bookingStatus: "not_started",
      paymentStatus: "authorization_failed",
      transferStatus: "blocked",
      hotelPropertyId: hotelNavona,
      tourOperatorId: toRomaElite,
      tourId: tourFood,
      grossAmountCents: 8900,
      serviceEndAt: future.toISOString(),
    },
    {
      id: "order-confirm-failed",
      correlationId: "corr-004",
      overallStatus: "cancelled" as const,
      holdStatus: "released",
      bookingStatus: "failed",
      paymentStatus: "cancelled",
      transferStatus: "blocked",
      hotelPropertyId: hotelAurelia,
      tourOperatorId: toImperial,
      tourId: tourGolf,
      grossAmountCents: 9900,
      serviceEndAt: future.toISOString(),
    },
    {
      id: "order-capture-failed",
      correlationId: "corr-005",
      overallStatus: "manual_review" as const,
      holdStatus: "released",
      bookingStatus: "confirmed",
      paymentStatus: "capture_failed",
      transferStatus: "blocked",
      hotelPropertyId: hotelAurelia,
      tourOperatorId: toRomaElite,
      tourId: tourTivoli,
      grossAmountCents: 19900,
      providerBookingId: "BK-CAPTURE-FAIL",
      serviceEndAt: future.toISOString(),
    },
    {
      id: "order-pending-settlement",
      correlationId: "corr-006",
      overallStatus: "completed" as const,
      holdStatus: "released",
      bookingStatus: "confirmed",
      paymentStatus: "captured",
      transferStatus: "eligible",
      fulfilmentStatus: "completed",
      hotelPropertyId: hotelNavona,
      tourOperatorId: toRomaElite,
      tourId: tourColosseum,
      grossAmountCents: 14900,
      capturedAt: past.toISOString(),
      transferEligibleAt: past.toISOString(),
      serviceEndAt: past.toISOString(),
      voucherCode: "TSB-VCH-006",
      touristEmail: "tourist6@demo.com",
    },
    {
      id: "order-settlement-done",
      correlationId: "corr-007",
      overallStatus: "closed" as const,
      holdStatus: "released",
      bookingStatus: "confirmed",
      paymentStatus: "captured",
      transferStatus: "paid",
      fulfilmentStatus: "completed",
      hotelPropertyId: hotelAurelia,
      tourOperatorId: toRomaElite,
      tourId: tourUnderground,
      grossAmountCents: 11900,
      capturedAt: past.toISOString(),
      transferEligibleAt: past.toISOString(),
      serviceEndAt: past.toISOString(),
      stripeFeeCents: 375,
      toShareCents: 7962,
      hotelShareCents: 1190,
      tsbShareCents: 2373,
      voucherCode: "TSB-VCH-007",
    },
    {
      id: "order-refunded",
      correlationId: "corr-008",
      overallStatus: "cancelled" as const,
      holdStatus: "released",
      bookingStatus: "cancelled",
      paymentStatus: "refunded",
      transferStatus: "blocked",
      hotelPropertyId: hotelAurelia,
      tourOperatorId: toRomaElite,
      tourId: tourVatican,
      grossAmountCents: 12500,
      serviceEndAt: past.toISOString(),
    },
    {
      id: "order-to-cancel-debt",
      correlationId: "corr-009",
      overallStatus: "cancelled" as const,
      holdStatus: "released",
      bookingStatus: "cancelled",
      paymentStatus: "refunded",
      transferStatus: "reversed",
      fulfilmentStatus: "operator_cancelled",
      hotelPropertyId: hotelNavona,
      tourOperatorId: toRomaElite,
      tourId: tourFood,
      grossAmountCents: 8900,
      serviceEndAt: past.toISOString(),
    },
    {
      id: "order-archived",
      correlationId: "corr-010",
      overallStatus: "closed" as const,
      holdStatus: "released",
      bookingStatus: "confirmed",
      paymentStatus: "captured",
      transferStatus: "paid",
      fulfilmentStatus: "completed",
      hotelPropertyId: hotelAurelia,
      tourOperatorId: toRomaElite,
      tourId: tourColosseum,
      grossAmountCents: 14900,
      capturedAt: past.toISOString(),
      serviceEndAt: past.toISOString(),
      voucherCode: "TSB-VCH-010",
    },
  ];

  return {
    cities: [
      {
        id: CID.rome,
        name: "Rome",
        country: "Italy",
        slug: "rome",
        timezone: "Europe/Rome",
        currency: "EUR",
        languages: ["en", "it"],
        status: "active",
        isActive: true,
      },
      {
        id: CID.london,
        name: "London",
        country: "United Kingdom",
        slug: "london",
        timezone: "Europe/London",
        currency: "GBP",
        languages: ["en"],
        status: "preview",
        isActive: true,
      },
      {
        id: CID.tokyo,
        name: "Tokyo",
        country: "Japan",
        slug: "tokyo",
        timezone: "Asia/Tokyo",
        currency: "JPY",
        languages: ["en", "ja"],
        status: "inactive",
        isActive: false,
      },
    ],
    categories: [
      { id: catAncient, cityId: CID.rome, name: "Ancient Rome", sortOrder: 1, isActive: true },
      { id: catVatican, cityId: CID.rome, name: "Vatican & Religious", sortOrder: 2, isActive: true },
      { id: catFood, cityId: CID.rome, name: "Food & Wine", sortOrder: 3, isActive: true },
      { id: catUnique, cityId: CID.rome, name: "Unique Experiences", sortOrder: 4, isActive: true },
      { id: catDayTrips, cityId: CID.rome, name: "Day Trips", sortOrder: 5, isActive: true },
    ],
    tours: [
      {
        id: tourColosseum,
        cityId: CID.rome,
        categoryId: catAncient,
        title: "Colosseum Private Access",
        description: "Skip-the-line private access to the Colosseum with expert historian guide.",
        meetingPoint: "Colosseum Metro Stop B",
        restrictions: "Moderate fitness required. No large bags.",
        imageUrl: "/tours/colosseum.jpg",
        durationHours: 3,
        status: "published",
        adultPriceCents: 14900,
        childPriceCents: 8900,
      },
      {
        id: tourVatican,
        cityId: CID.rome,
        categoryId: catVatican,
        title: "Vatican Early Entry",
        description: "Enter the Vatican Museums before public opening hours.",
        meetingPoint: "Vatican Museums Entrance",
        restrictions: "Dress code: shoulders and knees covered.",
        imageUrl: "/tours/vatican.jpg",
        durationHours: 4,
        status: "published",
        adultPriceCents: 12500,
        childPriceCents: 7500,
      },
      {
        id: tourFood,
        cityId: CID.rome,
        categoryId: catFood,
        title: "Roman Food and Wine Walk",
        description: "Trastevere culinary journey with local wine pairings.",
        meetingPoint: "Piazza Trilussa",
        restrictions: "Age 18+ for wine. Dietary restrictions accommodated.",
        imageUrl: "/tours/food.jpg",
        durationHours: 3,
        status: "published",
        adultPriceCents: 8900,
        childPriceCents: 5900,
      },
      {
        id: tourGolf,
        cityId: CID.rome,
        categoryId: catUnique,
        title: "Sunset Golf Cart Tour",
        description: "Rome by golf cart at golden hour.",
        meetingPoint: "Piazza del Popolo",
        restrictions: "Max 4 per cart.",
        imageUrl: "/tours/golf.jpg",
        durationHours: 2,
        status: "published",
        adultPriceCents: 9900,
        childPriceCents: 6900,
      },
      {
        id: tourTivoli,
        cityId: CID.rome,
        categoryId: catDayTrips,
        title: "Tivoli Villas Day Trip",
        description: "Hadrian's Villa and Villa d'Este gardens.",
        meetingPoint: "Termini Station",
        restrictions: "Full day. Lunch not included.",
        imageUrl: "/tours/tivoli.jpg",
        durationHours: 8,
        status: "published",
        adultPriceCents: 19900,
        childPriceCents: 12900,
      },
      {
        id: tourUnderground,
        cityId: CID.rome,
        categoryId: catAncient,
        title: "Underground Rome Experience",
        description: "Crypts, catacombs, and hidden layers beneath the city.",
        meetingPoint: "Basilica San Clemente",
        restrictions: "Not suitable for claustrophobia.",
        imageUrl: "/tours/underground.jpg",
        durationHours: 3,
        status: "published",
        adultPriceCents: 11900,
        childPriceCents: 7900,
      },
    ],
    hotelGroups: [
      { id: "group-aurelia", name: "Aurelia Hospitality Group", organizationId: orgAurelia },
      { id: "group-thames", name: "Thames Luxury Collection", organizationId: orgThames },
    ],
    hotelProperties: [
      {
        id: hotelAurelia,
        groupId: "group-aurelia",
        cityId: CID.rome,
        organizationId: orgAurelia,
        name: "Hotel Aurelia Roma",
        brandColor: "#8B4513",
        logoInitial: "A",
        qrToken: "H8kX2mRomaA1bC3dE5fG7h",
        stripeAccountId: "acct_hotel_aurelia_test",
        status: "active",
      },
      {
        id: hotelNavona,
        groupId: "group-aurelia",
        cityId: CID.rome,
        organizationId: orgAurelia,
        name: "Palazzo Navona Suites",
        brandColor: "#1e3a5f",
        logoInitial: "N",
        qrToken: "V9nY4pVenB2cD4eF6gH8i",
        stripeAccountId: "acct_hotel_navona_test",
        status: "active",
      },
      {
        id: hotelKensington,
        groupId: "group-thames",
        cityId: CID.london,
        organizationId: orgThames,
        name: "Kensington Grand Hotel",
        brandColor: "#065f46",
        logoInitial: "K",
        qrToken: "K3nS1ngt0nGr4ndH0t3l",
        stripeAccountId: "acct_hotel_kensington_test",
        status: "preview",
      },
    ],
    tourOperators: [
      {
        id: toRomaElite,
        organizationId: orgRomaElite,
        cityId: CID.rome,
        name: "Roma Elite Experiences",
        aggregatorId: "AGG-ROMA-ELITE",
        stripeAccountId: "acct_to_roma_elite_test",
        status: "active",
        priorityRank: 1,
        reliabilityScore: 98,
        allocationWeight: 50,
      },
      {
        id: toImperial,
        organizationId: orgImperial,
        cityId: CID.rome,
        name: "Imperial City Tours",
        aggregatorId: "AGG-IMPERIAL",
        stripeAccountId: "acct_to_imperial_test",
        status: "active",
        priorityRank: 2,
        reliabilityScore: 85,
        allocationWeight: 30,
        simulateTimeout: true,
      },
      {
        id: toHidden,
        organizationId: orgHidden,
        cityId: CID.rome,
        name: "Hidden Rome Collective",
        aggregatorId: "AGG-HIDDEN",
        stripeAccountId: "acct_to_hidden_test",
        status: "suspended",
        priorityRank: 3,
        reliabilityScore: 70,
        allocationWeight: 20,
      },
    ],
    operatorTourMappings: [
      tourColosseum,
      tourVatican,
      tourFood,
      tourGolf,
      tourTivoli,
      tourUnderground,
    ].flatMap((tourId) =>
      [toRomaElite, toImperial].map((toId, i) => ({
        id: `map-${tourId}-${toId}`,
        tourOperatorId: toId,
        tourId,
        isActive: true,
      }))
    ),
    orders: baseOrders.map((o) => ({
      id: o.id,
      correlationId: o.correlationId,
      cityId: CID.rome,
      hotelPropertyId: o.hotelPropertyId,
      tourOperatorId: o.tourOperatorId,
      tourId: o.tourId,
      hotelOrgId: o.hotelPropertyId === hotelKensington ? orgThames : orgAurelia,
      toOrgId:
        o.tourOperatorId === toImperial
          ? orgImperial
          : o.tourOperatorId === toHidden
            ? orgHidden
            : orgRomaElite,
      participants: { adults: 1, children: 0 },
      selectedDate: future.toISOString().split("T")[0],
      selectedTime: "09:00",
      selectedLanguage: "en",
      grossAmountCents: o.grossAmountCents,
      currency: "EUR",
      serviceEndAt: o.serviceEndAt,
      overallStatus: o.overallStatus,
      availabilityStatus: "available",
      holdStatus: o.holdStatus,
      bookingStatus: o.bookingStatus,
      paymentStatus: o.paymentStatus,
      fulfilmentStatus: (o as { fulfilmentStatus?: string }).fulfilmentStatus ?? "upcoming",
      transferStatus: o.transferStatus,
      holdId: (o as { holdId?: string }).holdId,
      holdExpiresAt: (o as { holdExpiresAt?: string }).holdExpiresAt,
      providerBookingId: (o as { providerBookingId?: string }).providerBookingId,
      voucherCode: (o as { voucherCode?: string }).voucherCode,
      capturedAt: (o as { capturedAt?: string }).capturedAt,
      transferEligibleAt: (o as { transferEligibleAt?: string }).transferEligibleAt,
      stripeFeeCents: (o as { stripeFeeCents?: number }).stripeFeeCents,
      toShareCents: (o as { toShareCents?: number }).toShareCents,
      hotelShareCents: (o as { hotelShareCents?: number }).hotelShareCents,
      tsbShareCents: (o as { tsbShareCents?: number }).tsbShareCents,
      touristEmail: (o as { touristEmail?: string }).touristEmail,
      createdAt: past.toISOString(),
      updatedAt: now.toISOString(),
    })),
    sagaEvents: [],
    ledgerEntries: [],
    auditLogs: [
      {
        id: "audit-001",
        actor: "superadmin@tsb-demo.com",
        action: "city.created",
        entity: "city",
        entityId: CID.rome,
        newValue: "Rome activated",
        correlationId: "seed-001",
        createdAt: past.toISOString(),
      },
    ],
    notifications: [],
    partnerDebts: [
      {
        id: "debt-001",
        tourOperatorId: toRomaElite,
        orderId: "order-to-cancel-debt",
        amountCents: 6230,
        reason: "TO cancellation — 70% recovery",
        status: "open",
        createdAt: past.toISOString(),
      },
    ],
    emailLogs: [],
    demoUsers: [
      {
        id: "user-superadmin",
        email: "superadmin@tsb-demo.com",
        password: "demo123!",
        role: "superadmin",
        name: "TSB SuperAdmin",
        organizationId: orgTsb,
      },
      {
        id: "user-to-owner",
        email: "to.owner@tsb-demo.com",
        password: "demo123!",
        role: "to_owner",
        name: "Marco Rossi",
        organizationId: orgRomaElite,
        tourOperatorId: toRomaElite,
      },
      {
        id: "user-hotel-group",
        email: "hotel.group@tsb-demo.com",
        password: "demo123!",
        role: "hotel_group",
        name: "Elena Aurelia",
        organizationId: orgAurelia,
      },
      {
        id: "user-hotel-property",
        email: "hotel.property@tsb-demo.com",
        password: "demo123!",
        role: "hotel_property",
        name: "Giulia Reception",
        organizationId: orgAurelia,
        hotelPropertyId: hotelAurelia,
      },
      {
        id: "user-support",
        email: "support@tsb-demo.com",
        password: "demo123!",
        role: "support",
        name: "TSB Support",
        organizationId: orgTsb,
      },
    ],
    simulation: {
      providerTimeout: false,
      providerUnavailable: false,
      holdFail: false,
      authFail: false,
      confirmFail: false,
      confirmAmbiguous: false,
      captureFail: false,
      transferFail: false,
      demoClockOffsetHours: 0,
    },
    processedWebhookIds: new Set(),
    idempotencyKeys: new Set(),
  };
}
